In [1]:
import numpy as np

In [6]:
X = np.array([2,3,5,1]) # 1D array
X2d = np.array([[1,2,3],[4,5,6]]) # 2D array
X3d = np.array([[[1,3],[4,2]],[[2,1],[3,4]]]) # 3D array
print(X)
print(X2d)
print(X3d)

[2 3 5 1]
[[1 2 3]
 [4 5 6]]
[[[1 3]
  [4 2]]

 [[2 1]
  [3 4]]]


In [9]:
# Sequential matrix, np.arange() and np.linspace()
np.arange(0, 10, .2).reshape(5, 10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [16]:
np.linspace(0, 15, 100).reshape(25, 4)

array([[ 0.        ,  0.15151515,  0.3030303 ,  0.45454545],
       [ 0.60606061,  0.75757576,  0.90909091,  1.06060606],
       [ 1.21212121,  1.36363636,  1.51515152,  1.66666667],
       [ 1.81818182,  1.96969697,  2.12121212,  2.27272727],
       [ 2.42424242,  2.57575758,  2.72727273,  2.87878788],
       [ 3.03030303,  3.18181818,  3.33333333,  3.48484848],
       [ 3.63636364,  3.78787879,  3.93939394,  4.09090909],
       [ 4.24242424,  4.39393939,  4.54545455,  4.6969697 ],
       [ 4.84848485,  5.        ,  5.15151515,  5.3030303 ],
       [ 5.45454545,  5.60606061,  5.75757576,  5.90909091],
       [ 6.06060606,  6.21212121,  6.36363636,  6.51515152],
       [ 6.66666667,  6.81818182,  6.96969697,  7.12121212],
       [ 7.27272727,  7.42424242,  7.57575758,  7.72727273],
       [ 7.87878788,  8.03030303,  8.18181818,  8.33333333],
       [ 8.48484848,  8.63636364,  8.78787879,  8.93939394],
       [ 9.09090909,  9.24242424,  9.39393939,  9.54545455],
       [ 9.6969697 ,  9.

In [ ]:
# randomized matrix with np.random
# np.random.rand()
print(np.random.rand(2,2)) # 0 to 1

# np.random.randn() # normal distribution
print(np.random.randn(3,3)) # normal distribution

# np.random.randint()
print(np.random.randint(-10,10,(3,3))) # random int from -10 to 10

# np.random.uniform()
print(np.random.uniform(0,2,(3,3))) # random uniform from 0 to 2

# np.random.permutation()
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10])) # random permutation

In [ ]:
a = np.random.randint(-10,10, (3,3))
b = np.random.randint(-10,10, (3,3))
print(a)
print(b)

In [ ]:
# matrix and constant operations
a ** 2 # + - * / ** % //

In [ ]:
# same size matrix operations
print(a + b)
print(a - b)
print(a / b)
print(a * b) # element-wise multiplication
print(a @ b) # matrix multiplication

In [ ]:
# matrix multiplication
np.matmul(a, b) # or np.dot(a, b) or a @ b