In [7]:
import numpy as np

In [8]:
x = np.array([2,3,5,1]) # 1D array
x2d = np.array([[1,2,3],[4,5,6]]) # 2D array
x3d = np.array([[[1,3],[4,2]],[[2,1],[3,4]]])
print(x)
print(x2d)
print(x3d)

[2 3 5 1]
[[1 2 3]
 [4 5 6]]
[[[1 3]
  [4 2]]

 [[2 1]
  [3 4]]]


In [9]:
# sequential matrix, np.arange() and np.linspace()
np.arange(0, 10, .2).reshape(5, 10)

array([[0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8],
       [2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8],
       [6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8],
       [8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [10]:
np.linspace(0, 15, 100)

array([ 0.        ,  0.15151515,  0.3030303 ,  0.45454545,  0.60606061,
        0.75757576,  0.90909091,  1.06060606,  1.21212121,  1.36363636,
        1.51515152,  1.66666667,  1.81818182,  1.96969697,  2.12121212,
        2.27272727,  2.42424242,  2.57575758,  2.72727273,  2.87878788,
        3.03030303,  3.18181818,  3.33333333,  3.48484848,  3.63636364,
        3.78787879,  3.93939394,  4.09090909,  4.24242424,  4.39393939,
        4.54545455,  4.6969697 ,  4.84848485,  5.        ,  5.15151515,
        5.3030303 ,  5.45454545,  5.60606061,  5.75757576,  5.90909091,
        6.06060606,  6.21212121,  6.36363636,  6.51515152,  6.66666667,
        6.81818182,  6.96969697,  7.12121212,  7.27272727,  7.42424242,
        7.57575758,  7.72727273,  7.87878788,  8.03030303,  8.18181818,
        8.33333333,  8.48484848,  8.63636364,  8.78787879,  8.93939394,
        9.09090909,  9.24242424,  9.39393939,  9.54545455,  9.6969697 ,
        9.84848485, 10.        , 10.15151515, 10.3030303 , 10.45

In [11]:
# randomized matrix with np.random
# np.random.rand()
print(np.random.rand(2,2)) # 0 to 1

# np.random.randn() # normal distribution
print(np.random.randn(3,3)) # normal distribution

# np.random.randint()
print(np.random.randint(-10,10,(3,3))) # random int from -10 to 10

# np.random.uniform()
print(np.random.uniform(0,2,(3,3))) # random uniform from 0 to 2

# np.random.permutation()
print(np.random.permutation([1,2,3,4,5,6,7,8,9,10])) # random permutation

[[0.47127327 0.56162926]
 [0.27923146 0.03118735]]
[[-0.73529527  0.46002155  0.41578297]
 [ 0.1039546  -1.04812226 -0.23991067]
 [ 1.04365603 -0.69685046 -0.12890193]]
[[ -4 -10  -9]
 [ -7   6   8]
 [-10   3  -4]]
[[1.92387347 0.42808582 0.88508327]
 [1.69833439 0.70026443 1.63986942]
 [1.94306174 0.16953493 0.10630665]]
[ 7  1  5  8  6  2  9  3  4 10]


operations

In [12]:
a = np.random.randint(-10,10, (3,3))
b = np.random.randint(-10,10, (3,3))
print(a)
print(b)

[[-6 -7  6]
 [-5 -3  1]
 [-8  3  5]]
[[ -4  -1  -1]
 [  8 -10   6]
 [  4   7   0]]


In [13]:
# matrix and constant operations
a ** 2 # + - * / ** % //

array([[36, 49, 36],
       [25,  9,  1],
       [64,  9, 25]])

In [14]:
# same size matrix operations
print(a + b)
print(a - b)
print(a / b)
print(a * b) # element-wise multiplication
print(a @ b) # matrix multiplication

[[-10  -8   5]
 [  3 -13   7]
 [ -4  10   5]]
[[ -2  -6   7]
 [-13   7  -5]
 [-12  -4   5]]
[[ 1.5         7.         -6.        ]
 [-0.625       0.3         0.16666667]
 [-2.          0.42857143         inf]]
[[ 24   7  -6]
 [-40  30   6]
 [-32  21   0]]
[[ -8 118 -36]
 [  0  42 -13]
 [ 76  13  26]]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11076\3732709816.py:4: RuntimeWarning: divide by zero encountered in divide
  print(a / b)


In [15]:
# matrix multiplication
np.matmul(a, b) # or np.dot(a, b) or a @ b

array([[ -8, 118, -36],
       [  0,  42, -13],
       [ 76,  13,  26]])

In [ ]:
# single element indexing
print(z[0,0], z[2, -1], z[5,5])

# single row 
print("fift row", z[4]) # 5th row ( index 4)

boolean filter

In [16]:
x = np.random.randint(1,6, (5, 5))
print(x)


[[1 5 5 4 2]
 [3 3 4 2 4]
 [1 5 1 1 4]
 [3 2 1 5 5]
 [1 1 4 3 2]]


In [17]:
x[x<3]

array([1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2])

In [18]:
x = np.random.randint(-10, 10, (5,5))
print(x)

x[(x>0) & (x<6)]

[[ -4  -9 -10   2   2]
 [  7   7   5   7  -3]
 [ -2  -2   3   9   9]
 [  6  -8   8   3   0]
 [ -1 -10   4   6  -9]]


array([2, 2, 5, 3, 3, 4])

In [21]:
x = np.random.randint(1, 10, (3,5))
print(x)
print(x.transpose())
print(x.T)
# flatten
print(x.flatten())
print(x.ravel())
# reshape
print(x.reshape(-1, 1)) # make a 2D array with column
print(x.reshape(1, -1)) # make a 3D array with colum

[[4 5 9 9 4]
 [8 8 8 6 2]
 [7 4 4 2 3]]
[[4 8 7]
 [5 8 4]
 [9 8 4]
 [9 6 2]
 [4 2 3]]
[[4 8 7]
 [5 8 4]
 [9 8 4]
 [9 6 2]
 [4 2 3]]
[4 5 9 9 4 8 8 8 6 2 7 4 4 2 3]
[4 5 9 9 4 8 8 8 6 2 7 4 4 2 3]
[[4]
 [5]
 [9]
 [9]
 [4]
 [8]
 [8]
 [8]
 [6]
 [2]
 [7]
 [4]
 [4]
 [2]
 [3]]
[[4 5 9 9 4 8 8 8 6 2 7 4 4 2 3]]


In [ ]:
# concatenate
x = np.array([1,2,3], [4,5,6])
y = np.array([3,2,1], [1,1,1])
print(x)
print(y)
print(np.concatenate([x, y], axis=0)) # axis=0: row
print(np.concatenate([x, y], axis=1)) # axis=1: column

In [ ]:
#stackimg
a = np.random.randint(0,10,(2,3))
b = np.random.randint(0,10,(2,3))
print(np.vstack((a,b))) # vertical